language: node_js
node_js:
    - "stable"
cache:
  directories:
    - "node_modules"
install:
    - yarn add codecov
script:
    - nyc cover mocha --exit --reporter lcovonly -- -R spec
    - codecov            