services: docker
before_install:
  - docker -v
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  - yarn run build

script:
  - yarn test

language: node_js

node_js:
    - "stable"
cache:
  directories:
    - "node_modules"
after_success:
    - yarn coverage