FROM node:11.14.0-alpine
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
WORKDIR /home/nodejs/app
ENV NODE_ENV prod
COPY package*.json ./
RUN yarn install --only=production
ARG port=5000
EXPOSE $port
COPY . ./
CMD /wait && node app.js